packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  '@sentry-internal/node-cpu-profiler': true
  msgpackr-extract: true
  prisma: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
