// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI / Migrate should use a direct DB connection (not pooler)
    // Fall back to DATABASE_URL so containerized migrate deploy does not fail
    // when only the pooled URL is present in the runtime env.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
