const STATE_CODE_MAP: Record<string, string> = {
  AP: "AP",
  "ANDHRA PRADESH": "AP",
  AR: "AR",
  "ARUNACHAL PRADESH": "AR",
  AS: "AS",
  ASSAM: "AS",
  BR: "BR",
  BIHAR: "BR",
  CG: "CG",
  CHHATTISGARH: "CG",
  GA: "GA",
  GOA: "GA",
  GJ: "GJ",
  GUJARAT: "GJ",
  HR: "HR",
  HARYANA: "HR",
  HP: "HP",
  "HIMACHAL PRADESH": "HP",
  JH: "JH",
  JHARKHAND: "JH",
  KA: "KA",
  KARNATAKA: "KA",
  KL: "KL",
  KERALA: "KL",
  MP: "MP",
  "MADHYA PRADESH": "MP",
  MH: "MH",
  MAHARASHTRA: "MH",
  MN: "MN",
  MANIPUR: "MN",
  ML: "ML",
  MEGHALAYA: "ML",
  MZ: "MZ",
  MIZORAM: "MZ",
  NL: "NL",
  NAGALAND: "NL",
  OD: "OD",
  ODISHA: "OD",
  ORISSA: "OD",
  PB: "PB",
  PUNJAB: "PB",
  RJ: "RJ",
  RAJASTHAN: "RJ",
  SK: "SK",
  SIKKIM: "SK",
  TN: "TN",
  "TAMIL NADU": "TN",
  TS: "TS",
  TELANGANA: "TS",
  TR: "TR",
  TRIPURA: "TR",
  UP: "UP",
  "UTTAR PRADESH": "UP",
  UK: "UK",
  UTTARAKHAND: "UK",
  WB: "WB",
  "WEST BENGAL": "WB",
  AN: "AN",
  "ANDAMAN AND NICOBAR ISLANDS": "AN",
  CH: "CH",
  CHANDIGARH: "CH",
  DN: "DN",
  "DADRA AND NAGAR HAVELI": "DN",
  DD: "DD",
  DAMAN: "DD",
  DIU: "DD",
  DL: "DL",
  DELHI: "DL",
  JK: "JK",
  "JAMMU AND KASHMIR": "JK",
  LA: "LA",
  LADAKH: "LA",
  LD: "LD",
  LAKSHADWEEP: "LD",
  PY: "PY",
  PUDUCHERRY: "PY",
  PONDICHERRY: "PY",
};

const normalizeStateInput = (value: string) =>
  value.trim().toUpperCase().replace(/\./g, "").replace(/\s+/g, " ");

export const toStateCode = (value: string): string => {
  const normalized = normalizeStateInput(value);
  return STATE_CODE_MAP[normalized] ?? normalized;
};
